### ISSUE TITLE
flavor categories design

### ISSUE THREAD

**Issue by moyalo** [mdivani/Ice-cream#2]
please make it exactly as it is on

http://mariannesicecream.com/flavors/

specifically:
    font-family: Pacifico;
    font-size: 22px;
    color: #C41230;

also use same color for the highlight of flavors

**Comment by mdivani** [comment]
Oz, 
 font-family is Pacifico and highlights are same colors as well already, I will change font-size to 22px, also I think it will be bit to much for mobile device but we can always adjust it easily

Edit.. my bad 22px look pretty good and color was different, fixed it all.

**Comment by mdivani** [comment]
issue is fixed
